// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSnhMnKyobm8zC7oMLpKi_EfGMJh_QEb4',
    appId: '1:571030665969:web:91df12a752fdb7319b8750',
    messagingSenderId: '571030665969',
    projectId: 'yodacentral-7a968',
    authDomain: 'yodacentral-7a968.firebaseapp.com',
    storageBucket: 'yodacentral-7a968.appspot.com',
    measurementId: 'G-6RZT4RFKDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC23Mw9k7M4RnCzXS2lzIhsVbWZlom7_NQ',
    appId: '1:571030665969:android:60f0c30c81068fb49b8750',
    messagingSenderId: '571030665969',
    projectId: 'yodacentral-7a968',
    storageBucket: 'yodacentral-7a968.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvWIFbBhN8hSTofvUQhEbYnIwuRYB_bkQ',
    appId: '1:571030665969:ios:3e344ba009d35add9b8750',
    messagingSenderId: '571030665969',
    projectId: 'yodacentral-7a968',
    storageBucket: 'yodacentral-7a968.appspot.com',
    iosBundleId: 'com.example.yodacentralSona',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvWIFbBhN8hSTofvUQhEbYnIwuRYB_bkQ',
    appId: '1:571030665969:ios:2707710fd4fbafda9b8750',
    messagingSenderId: '571030665969',
    projectId: 'yodacentral-7a968',
    storageBucket: 'yodacentral-7a968.appspot.com',
    iosBundleId: 'com.example.yodacentralSona.RunnerTests',
  );
}
